export const METRIC_DESCRIPTIONS: Record<string, string> = {
  ocr: "Official Cash Rate set by the RBNZ — influences mortgage and savings rates.",
  cpi: "Consumer Price Index — annual change in prices for a basket of goods.",
  gdp_growth: "Quarterly GDP growth rate — total economic output change.",
  unemployment: "Percentage of the labour force actively seeking work.",
  wage_growth: "Annual change in average hourly earnings.",
  median_income:
    "Average annual income from Stats NZ Quarterly Employment Survey.",
  house_price_median:
    "National median house price from REINZ, published monthly.",
  house_price_index: "REINZ House Price Index — tracks property value changes.",
  mortgage_floating: "Average floating mortgage rate across major NZ banks.",
  mortgage_1yr:
    "Average 1-year fixed mortgage rate, published weekly by the RBNZ.",
  mortgage_2yr: "Average 2-year fixed mortgage rate across major NZ banks.",
  nzd_usd:
    "NZ dollar against US dollar — weaker Kiwi makes imports more expensive.",
  nzd_aud: "NZ dollar against Australian dollar.",
  nzd_eur: "NZ dollar against Euro.",
  petrol_91: "Average 91 octane petrol price per litre from Gaspy.",
  petrol_95: "Average 95 octane petrol price per litre from Gaspy.",
  petrol_diesel: "Average diesel price per litre from Gaspy.",
  electricity_wholesale: "National average wholesale electricity spot price.",
  milk: "Average price of 2L standard milk across NZ supermarkets.",
  eggs: "Average price of a dozen eggs across NZ supermarkets.",
  bread: "Average price of a 600g white loaf across NZ supermarkets.",
  butter: "Average price of 500g salted butter across NZ supermarkets.",
  cheese: "Average price of 1kg mild cheddar across NZ supermarkets.",
  bananas: "Average price of bananas per kg across NZ supermarkets.",
  nzx_50: "NZX 50 Index — benchmark for the NZ share market.",
  minimum_wage: "NZ minimum wage per hour, updated annually on 1 April.",
};

export const METRIC_SENTIMENT: Record<string, "up_is_good" | "down_is_good"> = {
  petrol_91: "down_is_good",
  petrol_95: "down_is_good",
  petrol_diesel: "down_is_good",
  electricity_wholesale: "down_is_good",
  milk: "down_is_good",
  eggs: "down_is_good",
  bread: "down_is_good",
  butter: "down_is_good",
  cheese: "down_is_good",
  bananas: "down_is_good",
  cpi: "down_is_good",
  unemployment: "down_is_good",
  mortgage_1yr: "down_is_good",
  mortgage_2yr: "down_is_good",
  mortgage_floating: "down_is_good",
  house_price_median: "down_is_good",
  ocr: "down_is_good",
  nzd_usd: "up_is_good",
  nzd_aud: "up_is_good",
  nzd_eur: "up_is_good",
  nzx_50: "up_is_good",
  gdp_growth: "up_is_good",
  wage_growth: "up_is_good",
  median_income: "up_is_good",
  minimum_wage: "up_is_good",
};
